update_hotel_business_date:
  cron: "*/5 * * * *"
  class: UpdateHotelBusinessDate
  queue: high
  description: "This job updates all outdated business dates for hotels from the external PMS every 5 minutes"

checkin_notifier:
  cron: "0 55 7 * * *"
  class: CheckinNotifier
  queue: high
  description: "This job will trigger notification for a user check in once a day at 7:55 AM"

checkout_notifier:
  cron: "0 55 7 * * *"
  class: CheckoutNotifier
  queue: high
  description: "This job will trigger notification for a user check out once a day at 7:55 AM"

notification_pusher:
  cron: "1 * * * * *"
  class: NotificationSender
  queue: high
  description: "This job will trigger push notification"

email_notification_pusher:
  cron: "*/1 * * * *"
  class: EmailNotificationSender
  queue: high
  description: "This job will trigger email notification every minute"

queue_pre_checkin_reservations_scheduler:
  cron:  "*/10 * * * *"
  class: QueuePreCheckinReservationsScheduler
  queue: high
  description: "This job will trigger queue pre checkin reservations scheduler every 10 minutes"

reservation_import_scheduler:
  cron: "30 * * * * *"
  class: ReservationImportScheduler
  queue: high
  description: "This job will schedule the import job for the appropriate hotels every minute"

smartband_import_scheduler:
  cron: "0,30 * * * *"
  class: SmartbandImportScheduler
  queue: high
  description: "This job will schedule the smart band import for hotels"

external_references_import_scheduler:
  cron: "45 * * * * *"
  class: ExternalReferencesImportScheduler
  queue: high
  description: "This job will schedule the external references import job for the appropriate hotels every minute"

pre_reservation_scheduler:
  cron: "*/5 * * * *"
  class: PreReservationScheduler
  queue: high
  description: "This job will trigger every 5min and delete the pre_reservations table entries which are expired(updated > 20 minutes)"

upcoming_reservations_export_scheduler:
  cron: "0 0 * * *"
  class: UpcomingReservationsExportScheduler
  queue: high
  description: "This job will schedule the export job for the hotels every month on 1st"

campaign_recurring_notifier:
  cron: "*/5 * * * *"
  class: CampaignRecurringNotifier
  queue: high
  description: "This job will trigger every 5min and add entries to notification details table for recurring campaigns"

last_month_reservations_export_scheduler:
  cron: "0 0 1 * *"
  class: LastMonthReservationsExportScheduler
  queue: high
  description: "This job will schedule the export job for the hotels every month on 1st"
