source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '~> 3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '~> 0.3.13'

gem 'logging-rails', '~> 0.4.0', require: 'logging/rails'
gem 'quiet_assets', '~> 1.0.2', group: :development

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '~> 2.2.1'
end

gem 'jquery-rails', '~> 2.3.0'
gem 'jquery-ui-rails', '~> 4.0.4'
gem 'touchpunch-rails', '~> 1.0.1'
gem 'fog', '~> 1.15.0'
gem 'therubyracer', '~> 0.11.4'
gem 'jbuilder', '~> 2.0.5'

gem 'less-rails', '~> 2.4.2'

gem 'dalli', '~> 2.6.4'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
gem 'unicorn-rails', '~> 1.1.0'
gem 'unicorn-worker-killer', '~> 0.4.2'

# Deploy with Capistrano
# gem 'capistrano'

group :development do
  gem 'debugger', '~> 1.6.2'
  gem 'rubocop', '~> 0.20.0'
  gem 'sourcify'
end

gem 'god', '~> 0.13.2'
gem 'resque', '~> 1.24.1'
gem 'resque-scheduler', '~> 2.0.1'
gem 'resque-logger', '~> 0.2.0'
gem 'resque-loner', '~> 1.3.0'
gem 'redis-objects', '~> 0.7.0'

gem 'cancan', '~> 1.6.10'
gem 'savon', '~> 2.2.0'
gem 'kaminari'
group :development, :test do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'factory_girl_rails', '~> 4.2.1'
end

group :test do
  gem 'resque_spec', '~> 0.14.2' # This gem is for the TEST ENV ONLY. If in development, it will not execute jobs.
end

gem 'omniauth-facebook', '~> 1.4.1'
gem 'rest-client', '~> 1.6.7'
gem 'andand', '~> 1.3.3'

group :development do
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler', '~> 1.0.0'
  gem 'capistrano-rails', '~> 1.0.0'
  gem 'capistrano-rvm', '~> 0.0.3'
  gem 'capistrano-npm', '~> 1.0.0'
  gem 'capistrano-grunt', '~> 0.0.4', github: 'roots/capistrano-grunt'
end

gem 'rqrcode_png', '~> 0.1.2'
gem 'userstamp', git: 'https://github.com/kimkong/userstamp.git'

group :rmagick do
  gem 'rmagick', '~> 2.13.2' # This gem used for managing Image Processing.
end

gem 'geocoder', '~> 1.1.8'

gem 'authlogic', '~> 3.3.0'
gem 'paperclip', '~> 3.5.4'
gem 'rails-settings-cached', '~> 0.2.4'
gem 'power_enum', '~> 1.3.4'
gem "haml-rails", '~> 0.4'
gem "bcrypt-ruby", '~> 3.1.2', :require => "bcrypt"

# For push notification - iOS
gem 'grocer', '~> 0.5.0'

# For push notification - Android
gem 'gcm', '~> 0.0.5'

# For caching
gem 'second_level_cache', '~> 1.6.2'

gem 'wash_out', '~> 0.9.0', github: 'StayNTouch/wash_out', ref: '106095fac08a4e1e4e567e7a3b57ca299d3abf6b'
gem 'httparty', '~> 0.12.0'
gem 'nokogiri', '~> 1.6.0'

gem 'credit_card_validator', '~> 1.2.0'

gem 'net-sftp', '~> 2.1.2'
gem 'strip_params', '~> 0.0.1'

gem 'globalize', '~> 3.1.0'
gem 'mail_view', '~> 2.0.4'
gem 'validates_overlap'

gem 'digest-crc', '~> 0.4.1'

gem 'exception_notification'

gem 'letter_opener', group: :development

gem "validate_url"

gem "eventmachine"
gem "bunny", "~> 1.4.0"

#Wicked PDF uses the shell utility wkhtmltopdf to serve a PDF file to a user from HTML
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
