module SeedMembershipTypes
  def create_membership_types
    MembershipType.create(membership_class: :FFP, value: 'AA', description: 'American Airlines (AAdvantage)')
    MembershipType.create(membership_class: :FFP, value: 'AC', description: 'Air Canada (Aeroplan)')
    MembershipType.create(membership_class: :FFP, value: 'AF', description: 'Air France (Flying Blue)')
    MembershipType.create(membership_class: :FFP, value: 'AK', description: 'Alaska Airlines (Mileage Plan)')
    MembershipType.create(membership_class: :FFP, value: 'AL', description: 'Aloha Airlines (AlohaPass)')
    MembershipType.create(membership_class: :FFP, value: 'AM', description: 'AeroMexico (Club Premier)')
    MembershipType.create(membership_class: :FFP, value: 'AN', description: 'All Nippon Airways (ANA Mileage Club)')
    MembershipType.create(membership_class: :FFP, value: 'AR', description: 'Aerolineas Argentinas (Plus Program)')
    MembershipType.create(membership_class: :FFP, value: 'AS', description: 'Asiana (Asiana Club)')
    MembershipType.create(membership_class: :FFP, value: 'AT', description: 'ATA (Travel Awards)')
    MembershipType.create(membership_class: :FFP, value: 'AW', description: 'America West (FlightFund)')
    MembershipType.create(membership_class: :FFP, value: 'AU', description: 'Austrian Airlines (Miles & More)')
    MembershipType.create(membership_class: :FFP, value: 'BA', description: 'British Airways (Executive Club)')
    MembershipType.create(membership_class: :FFP, value: 'CP', description: 'Cathay Pacific Airways (Asia Miles)')
    MembershipType.create(membership_class: :FFP, value: 'DL', description: 'Delta Air Lines (SkyMiles)')
    MembershipType.create(membership_class: :FFP, value: 'FI', description: 'Finnair (Plus)')
    MembershipType.create(membership_class: :FFP, value: 'FR', description: 'Frontier (EarlyReturns)')
    MembershipType.create(membership_class: :FFP, value: 'HI', description: 'Hawaiian Airlines (HawaiianMiles)')
    MembershipType.create(membership_class: :FFP, value: 'IA', description: 'Independence Air (iClub)')
    MembershipType.create(membership_class: :FFP, value: 'IB', description: 'Iberia (Plus)')
    MembershipType.create(membership_class: :FFP, value: 'IT', description: 'Alitalia Club (Mille Miglia)')
    MembershipType.create(membership_class: :FFP, value: 'JA', description: 'Japan Airlines (JAL Mileage Bank)')
    MembershipType.create(membership_class: :FFP, value: 'JB', description: 'JetBlue (TrueBlue)')
    MembershipType.create(membership_class: :FFP, value: 'KA', description: 'Korean Airlines (Skypass)')
    MembershipType.create(membership_class: :FFP, value: 'KL', description: 'KLM (Flying Blue)')
    MembershipType.create(membership_class: :FFP, value: 'LA', description: 'LAN (LAN Pass)')
    MembershipType.create(membership_class: :FFP, value: 'LI', description: 'Aer Lingus (Travel Award Bonus Program)')
    MembershipType.create(membership_class: :FFP, value: 'LU', description: 'Lufthansa (Miles & More)')
    MembershipType.create(membership_class: :FFP, value: 'MA', description: 'Malaysia Airlines (Enrich)')
    MembershipType.create(membership_class: :FFP, value: 'MW', description: 'Midwest Airlines (Midwest Miles)')
    MembershipType.create(membership_class: :FFP, value: 'MX', description: 'Mexicana (Frequenta)')
    MembershipType.create(membership_class: :FFP, value: 'NW', description: 'Northwest Airlines (WorldPerks)')
    MembershipType.create(membership_class: :FFP, value: 'NZ', description: 'Air New Zealand (Air Points)')
    MembershipType.create(membership_class: :FFP, value: 'QA', description: 'Qantas (Frequent Flyer)')
    MembershipType.create(membership_class: :FFP, value: 'SS', description: 'SAS (Euro Bonus)')
    MembershipType.create(membership_class: :FFP, value: 'SI', description: 'Singapore Airlines (KrisFlyer)')
    MembershipType.create(membership_class: :FFP, value: 'SA', description: 'Swiss Air (Miles & More)')
    MembershipType.create(membership_class: :FFP, value: 'SW', description: 'Southwest Airlines (Rapid Rewards)')
    MembershipType.create(membership_class: :FFP, value: 'TR', description: 'Air Tran (A Plus Rewards)')
    MembershipType.create(membership_class: :FFP, value: 'UA', description: 'United Airlines (Mileage Plus)')
    MembershipType.create(membership_class: :FFP, value: 'US', description: 'US Airways (Dividend Miles)')
    MembershipType.create(membership_class: :FFP, value: 'VA', description: 'Varig (Smiles)')
    MembershipType.create(membership_class: :FFP, value: 'VI', description: 'Virgin Atlantic (Flying Club)')
  end
end
